# The sequence of triangle numbers is generated by adding the natural numbers. 
# So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
#     
#     1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
# 
# Let us list the factors of the first seven triangle numbers:
#     
#     1: 1
# 3: 1,3
# 6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28
# We can see that 28 is the first triangle number to have over five divisors.
# 
# What is the value of the first triangle number to have over five hundred divisors?

TriangleNumber <- function(n) {
    # i is the triangle number index
    i <- 1
    divisors <- c()
    while (length(divisors)<n) {
        triangle.num <- sum(1:i)
        divisors <- Divisors(triangle.num)
        print(length(divisors))
        i <- i+1
    }
    triangle.num
}

Divisors <- function(n) {
    divs <- c(1,n)
    m <- 2
    max <- (n/2)+1
    while (m < max) {
        if (n%%m==0) divs <- c(divs, m, n/m)
        max <- ceiling(n/m)
        m <- m+1
    }
    unique(divs)
}


#test
TriangleNumber(5)==28

TriangleNumber(500)
# [1] 76576500

# Unit: milliseconds
# expr         min          lq        mean      median          uq         max neval
# TriangleNumber(50)    47.05857    47.05857    47.05857    47.05857    47.05857    47.05857     1
# TriangleNumber(500) 80793.40903 80793.40903 80793.40903 80793.40903 80793.40903 80793.40903     1

#O(n^2)
