# Consider all integer combinations of ab for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:
#     
# 22=4, 23=8, 24=16, 25=32
# 32=9, 33=27, 34=81, 35=243
# 42=16, 43=64, 44=256, 45=1024
# 52=25, 53=125, 54=625, 55=3125
# If they are then placed in numerical order, with any repeats removed, 
# we get the following sequence of 15 distinct terms:
#     
#     4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125
# 
# How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

DistinctPow <- function(n) {
    d <- c()
    for (a in 2:n) {
        for (b in 2:n) {
            d <- c(d, a^b) 
        }
    }
    length(unique(d))
}

# test
# DistinctPow(5)==15

# Unit: milliseconds
# expr      min       lq    mean   median      uq      max neval
# DistinctPow(100) 191.1756 231.5725 248.148 238.6935 265.198 366.8112   100
