# Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
#     
#     1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
# 
# It can be seen that P4 + P7 = 22 + 70 = 92 = P8. 
# However, their difference, 70 − 22 = 48, is not pentagonal.
# 
# Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal 
# and D = |Pk − Pj| is minimised; 
# 
# what is the value of D?

PentagonNumbers <- function() {
    i <- 1
    Found<-FALSE
    while(!Found) {
        i <- i+1
        n <- (i*((3*i)-1))/2
        j <- i-1
        while (j > 0) {
            m <- (j*(3*j-1))/2
            if (IsPent(n - m) && IsPent(n + m)) {
                Found <- TRUE
                result <- n-m
            }
            j <- j-1
        }
    }
    result
}

IsPent <- function(n) {
    ((1 + sqrt(24*n + 1))/6)%%1==0
}

# test
#IsPent(5)==TRUE
#IsPent(6)==FALSE

#a<-PentagonNumbers()

# Unit: seconds
# expr     min      lq    mean  median      uq     max neval
# PentagonNumbers() 7.95986 7.95986 7.95986 7.95986 7.95986 7.95986     1