# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:
#     
#     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# 
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms.

SumOddFib <- function(n) {
    sum <- 0
    f <- c(0,1)
    while (tail(f, 1) < n) {
        if (tail(f, 1)%%2 == 0) sum <- sum+tail(f, 1)
        f <- c(f, sum(tail(f, 2)))
    }
    sum
}

SumOddFib(4000000)
# [1] 4613732

# O(n)


